# Generated by Django 6.0.4 on 2026-06-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_promocion_detallepromocion'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='subtotal_servicios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cita',
            name='total_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetalleServicioCita',
            fields=[
                ('id_detalle_cita', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_detalle', to='citas.cita')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cita', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de servicio de cita',
                'verbose_name_plural': 'Detalles de servicios de cita',
                'db_table': '"agenda"."detalle_servicio_cita"',
                'ordering': ['id_detalle_cita'],
            },
        ),
    ]
