# Generated by Django 6.0.4 on 2026-06-22 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_poblar_detalles_servicios_cita'),
        ('seguridad', '0002_permiso_rolpermiso_permiso_roles'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionServicio',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ATENCION', 'En atencion'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('total_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listo_para_cobro', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='atenciones_servicio', to='seguridad.usuario')),
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='atenciones_recibidas', to='seguridad.usuario')),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='atencion_servicio', to='citas.cita')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_registradas', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Atencion de servicio',
                'verbose_name_plural': 'Atenciones de servicio',
                'db_table': '"agenda"."atencion_servicio"',
                'ordering': ['-fecha', '-hora_inicio', '-id_atencion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAtencionServicio',
            fields=[
                ('id_detalle_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('id_atencion', models.ForeignKey(db_column='id_atencion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='citas.atencionservicio')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_atencion', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de atencion de servicio',
                'verbose_name_plural': 'Detalles de atenciones de servicio',
                'db_table': '"agenda"."detalle_atencion_servicio"',
                'ordering': ['id_detalle_atencion'],
                'unique_together': {('id_atencion', 'id_servicio')},
            },
        ),
    ]
