# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_atencionservicio_detalleatencionservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionTrabajo',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion_interna', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estacion de trabajo',
                'verbose_name_plural': 'Estaciones de trabajo',
                'db_table': '"agenda"."estacion_trabajo"',
                'ordering': ['nombre'],
            },
        ),
    ]
