# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_estaciontrabajo'),
        ('seguridad', '0002_permiso_rolpermiso_permiso_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEstacionTrabajo',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_estacion', to='seguridad.usuario')),
                ('id_estacion', models.ForeignKey(db_column='id_estacion', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_barberos', to='citas.estaciontrabajo')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_estacion_registradas', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Asignacion de estacion de trabajo',
                'verbose_name_plural': 'Asignaciones de estaciones de trabajo',
                'db_table': '"agenda"."asignacion_estacion_trabajo"',
                'ordering': ['-fecha', 'hora_inicio', 'codigo_barbero'],
            },
        ),
    ]
