# Generated by Django 6.0.4 on 2026-06-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PROMOCION', 'Promocion'), ('NUEVO_BARBERO', 'Nuevo barbero'), ('CITA', 'Cita'), ('RECORDATORIO_CITA', 'Recordatorio de cita'), ('INVENTARIO', 'Inventario'), ('SISTEMA', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('rol_destino', models.CharField(blank=True, max_length=100)),
                ('enviada', models.BooleanField(default=False)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('PARCIAL', 'Parcial'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20)),
                ('enviados', models.PositiveIntegerField(default=0)),
                ('fallidos', models.PositiveIntegerField(default=0)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_destino', models.ForeignKey(blank=True, db_column='usuario_destino', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones_notificacion',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('navegador', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(db_column='codigo_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Suscripcion push',
                'verbose_name_plural': 'Suscripciones push',
                'db_table': 'notificaciones_push_subscription',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id_notificacion_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('leida', models.BooleanField(default=False)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(db_column='id_notificacion', on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='notificaciones.notificacion')),
                ('usuario', models.ForeignKey(db_column='codigo_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_usuario', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Notificacion de usuario',
                'verbose_name_plural': 'Notificaciones de usuarios',
                'db_table': 'notificaciones_notificacion_usuario',
                'ordering': ['-fecha_registro'],
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
    ]
