# Generated by Django 6.0.4 on 2026-06-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas_caja', '0004_venta_pagoventa_detalleventa_comisionventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ventas_caja.venta'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_nuevo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA_INICIAL', 'Entrada inicial'), ('AJUSTE', 'Ajuste'), ('ACTIVACION', 'Activacion'), ('DESACTIVACION', 'Desactivacion'), ('SALIDA_VENTA', 'Salida por venta'), ('DEVOLUCION', 'Devolucion')], max_length=20),
        ),
    ]
