# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='BORRADOR', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encuesta de satisfaccion',
                'verbose_name_plural': 'Encuestas de satisfaccion',
                'db_table': '"agenda"."encuesta_satisfaccion"',
                'ordering': ['-fecha_registro', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo_respuesta', models.CharField(choices=[('OPCION_UNICA', 'Opcion unica'), ('ESCALA', 'Escala'), ('TEXTO', 'Texto')], default='ESCALA', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('obligatoria', models.BooleanField(default=True)),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cliente.encuestasatisfaccion')),
            ],
            options={
                'verbose_name': 'Pregunta de encuesta',
                'verbose_name_plural': 'Preguntas de encuesta',
                'db_table': '"agenda"."pregunta_encuesta"',
                'ordering': ['id_encuesta', 'orden', 'id_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuestaEncuesta',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150)),
                ('valor', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cliente.preguntaencuesta')),
            ],
            options={
                'verbose_name': 'Opcion de respuesta de encuesta',
                'verbose_name_plural': 'Opciones de respuesta de encuesta',
                'db_table': '"agenda"."opcion_respuesta_encuesta"',
                'ordering': ['id_pregunta', 'orden', 'id_opcion'],
            },
        ),
    ]
