# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_asignacionestaciontrabajo'),
        ('cliente', '0001_initial'),
        ('seguridad', '0002_permiso_rolpermiso_permiso_roles'),
        ('servicios', '0003_recomendacioncuidado_detalleproductorecomendacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamoSugerencia',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitud', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('SUGERENCIA', 'Sugerencia')], max_length=20)),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revision'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='reclamos_sugerencias', to='seguridad.usuario')),
                ('id_cita', models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_sugerencias', to='citas.cita')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_sugerencias', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Reclamo o sugerencia',
                'verbose_name_plural': 'Reclamos y sugerencias',
                'db_table': '"agenda"."reclamo_sugerencia"',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
