# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_reclamosugerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamosugerencia',
            name='estado',
            field=models.CharField(
                choices=[
                    ('PENDIENTE', 'Pendiente'),
                    ('EN_REVISION', 'En revision'),
                    ('REVISADO', 'Revisado'),
                    ('RESUELTO', 'Resuelto'),
                    ('CERRADO', 'Cerrado'),
                    ('INACTIVO', 'Inactivo'),
                ],
                default='PENDIENTE',
                max_length=20,
            ),
        ),
    ]
