# Generated by Django 6.0.4 on 2026-07-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_asignacionestaciontrabajo'),
        ('cliente', '0003_reclamosugerencia_estado_revisado'),
        ('seguridad', '0004_permisolaboralpersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuestaSatisfaccion',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_encuestas', to='seguridad.usuario')),
                ('id_atencion', models.ForeignKey(db_column='id_atencion', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_encuesta', to='citas.atencionservicio')),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='cliente.encuestasatisfaccion')),
            ],
            options={
                'verbose_name': 'Respuesta de encuesta de satisfaccion',
                'verbose_name_plural': 'Respuestas de encuestas de satisfaccion',
                'db_table': '"agenda"."respuesta_encuesta_satisfaccion"',
                'ordering': ['-fecha_registro'],
                'unique_together': {('id_encuesta', 'id_atencion', 'codigo_cliente')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuestaEncuesta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True)),
                ('valor', models.PositiveIntegerField(blank=True, null=True)),
                ('id_opcion', models.ForeignKey(blank=True, db_column='id_opcion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_detalle', to='cliente.opcionrespuestaencuesta')),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_detalle', to='cliente.preguntaencuesta')),
                ('id_respuesta', models.ForeignKey(db_column='id_respuesta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cliente.respuestaencuestasatisfaccion')),
            ],
            options={
                'verbose_name': 'Detalle de respuesta de encuesta',
                'verbose_name_plural': 'Detalles de respuestas de encuesta',
                'db_table': '"agenda"."detalle_respuesta_encuesta"',
                'ordering': ['id_respuesta', 'id_pregunta'],
                'unique_together': {('id_respuesta', 'id_pregunta')},
            },
        ),
    ]
