# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete de servicio',
                'verbose_name_plural': 'Paquetes de servicios',
                'db_table': '"agenda"."paquete_servicio"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetallePaqueteServicio',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_paquete', models.ForeignKey(db_column='id_paquete', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicios', to='servicios.paqueteservicio')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_paquetes', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de paquete de servicio',
                'verbose_name_plural': 'Detalles de paquetes de servicios',
                'db_table': '"agenda"."detalle_paquete_servicio"',
                'ordering': ['id_paquete', 'id_servicio'],
                'unique_together': {('id_paquete', 'id_servicio')},
            },
        ),
        migrations.AddField(
            model_name='paqueteservicio',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='paquetes', through='servicios.DetallePaqueteServicio', to='servicios.servicio'),
        ),
    ]
