# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_asignacionestaciontrabajo'),
        ('inventario', '0002_movimientoinventario_id_venta_and_more'),
        ('seguridad', '0002_permiso_rolpermiso_permiso_roles'),
        ('servicios', '0002_paqueteservicio_detallepaqueteservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionCuidado',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('frecuencia_corte', models.CharField(blank=True, max_length=150)),
                ('cuidados_cabello', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='recomendaciones_realizadas', to='seguridad.usuario')),
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='recomendaciones_recibidas', to='seguridad.usuario')),
                ('id_atencion', models.ForeignKey(db_column='id_atencion', on_delete=django.db.models.deletion.PROTECT, related_name='recomendaciones_cuidado', to='citas.atencionservicio')),
            ],
            options={
                'verbose_name': 'Recomendacion de cuidado',
                'verbose_name_plural': 'Recomendaciones de cuidado',
                'db_table': '"agenda"."recomendacion_cuidado"',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductoRecomendacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recomendaciones', to='inventario.producto')),
                ('id_recomendacion', models.ForeignKey(db_column='id_recomendacion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='servicios.recomendacioncuidado')),
            ],
            options={
                'verbose_name': 'Detalle de producto recomendado',
                'verbose_name_plural': 'Detalles de productos recomendados',
                'db_table': '"agenda"."detalle_producto_recomendacion"',
                'ordering': ['id_recomendacion', 'id_producto'],
                'unique_together': {('id_recomendacion', 'id_producto')},
            },
        ),
        migrations.AddField(
            model_name='recomendacioncuidado',
            name='productos_sugeridos',
            field=models.ManyToManyField(blank=True, related_name='recomendaciones_cuidado', through='servicios.DetalleProductoRecomendacion', to='inventario.producto'),
        ),
    ]
