# Generated by Django 6.0.4 on 2026-07-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_asignacionestaciontrabajo'),
        ('seguridad', '0003_permisos_atenciones'),
        ('servicios', '0003_recomendacioncuidado_detalleproductorecomendacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCapilar',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cabello', models.CharField(max_length=120)),
                ('condicion_cuero_cabelludo', models.CharField(max_length=180)),
                ('observaciones', models.TextField(blank=True)),
                ('necesidades_detectadas', models.TextField()),
                ('cuidados_sugeridos', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_capilares_realizados', to='seguridad.usuario')),
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_capilares_recibidos', to='seguridad.usuario')),
                ('id_atencion', models.ForeignKey(blank=True, db_column='id_atencion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_capilares', to='citas.atencionservicio')),
                ('id_cita', models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_capilares', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Diagnostico capilar',
                'verbose_name_plural': 'Diagnosticos capilares',
                'db_table': '"agenda"."diagnostico_capilar"',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
