# Generated by Django 6.0.4 on 2026-07-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_asignacionestaciontrabajo'),
        ('seguridad', '0004_permisolaboralpersonal'),
        ('servicios', '0004_diagnosticocapilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoPortafolio',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estilo', models.CharField(max_length=150)),
                ('imagen_url', models.URLField(blank=True, max_length=500)),
                ('referencia', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=20)),
                ('observacion_revision', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_portafolio', to='seguridad.usuario')),
                ('id_atencion', models.ForeignKey(blank=True, db_column='id_atencion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_portafolio', to='citas.atencionservicio')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_portafolio', to='servicios.servicio')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='revisado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_portafolio_revisados', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Trabajo de portafolio',
                'verbose_name_plural': 'Trabajos de portafolio',
                'db_table': '"agenda"."trabajo_portafolio"',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
