# Generated by Django 6.0.4 on 2026-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_trabajoportafolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajoportafolio',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='trabajoportafolio',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='portafolio/trabajos/'),
        ),
    ]
