# Generated by Django 6.0.4 on 2026-06-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('ventas_caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('justificacion_cierre', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_usuario_apertura', models.ForeignKey(db_column='codigo_usuario_apertura', on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to='seguridad.usuario')),
                ('codigo_usuario_cierre', models.ForeignKey(blank=True, db_column='codigo_usuario_cierre', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'ventas_caja_caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ventas_caja.caja')),
                ('usuario', models.ForeignKey(blank=True, db_column='codigo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'db_table': 'ventas_caja_movimiento_caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
