# Generated by Django 6.0.4 on 2026-06-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('ventas_caja', '0002_caja_movimientocaja'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('estado',), name='ventas_caja_unica_caja_abierta'),
        ),
    ]
