# Generated by Django 6.0.4 on 2026-06-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_promocion_detallepromocion'),
        ('inventario', '0001_initial'),
        ('seguridad', '0001_initial'),
        ('servicios', '0001_initial'),
        ('ventas_caja', '0003_caja_ventas_caja_unica_caja_abierta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_cajero', models.ForeignKey(db_column='codigo_cajero', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_registradas', to='seguridad.usuario')),
                ('codigo_cliente', models.ForeignKey(blank=True, db_column='codigo_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cliente', to='seguridad.usuario')),
                ('id_cita', models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_caja_venta',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_venta', to='ventas_caja.metodopago')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas_caja.venta')),
            ],
            options={
                'verbose_name': 'Pago de venta',
                'verbose_name_plural': 'Pagos de venta',
                'db_table': 'ventas_caja_pago_venta',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_barbero', models.ForeignKey(blank=True, db_column='codigo_barbero', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_vendidos', to='seguridad.usuario')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.producto')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='servicios.servicio')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_caja.venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'ventas_caja_detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_venta', to='seguridad.usuario')),
                ('id_detalle', models.ForeignKey(db_column='id_detalle', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas_caja.detalleventa')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas_caja.venta')),
            ],
            options={
                'verbose_name': 'Comision de venta',
                'verbose_name_plural': 'Comisiones de venta',
                'db_table': 'ventas_caja_comision_venta',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
