# Generated by Django 6.0.4 on 2026-06-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_caja', '0004_venta_pagoventa_detalleventa_comisionventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, db_column='id_metodo_pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='ventas_caja.metodopago'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='id_pago_venta',
            field=models.ForeignKey(blank=True, db_column='id_pago_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas_caja.pagoventa'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas_caja.venta'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='naturaleza',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('INGRESO_MANUAL', 'Ingreso manual'), ('EGRESO', 'Egreso'), ('RETIRO', 'Retiro'), ('DEVOLUCION', 'Devolucion'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo')], default='INGRESO_MANUAL', max_length=30),
        ),
    ]
