# Generated by Django 6.0.4 on 2026-06-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_caja', '0005_movimientocaja_estado_movimientocaja_id_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoStripe',
            fields=[
                ('id_pago_stripe', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(max_length=120, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('stripe_status', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('REQUIERE_PAGO', 'Requiere pago'), ('PROCESANDO', 'Procesando'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_stripe', to='ventas_caja.venta')),
            ],
            options={
                'verbose_name': 'Pago Stripe',
                'verbose_name_plural': 'Pagos Stripe',
                'db_table': 'ventas_caja_pago_stripe',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
