# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_caja', '0006_pagostripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaCuotas',
            fields=[
                ('id_venta_cuotas', models.AutoField(primary_key=True, serialize=False)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='venta_cuotas', to='ventas_caja.venta')),
            ],
            options={
                'verbose_name': 'Venta por cuotas',
                'verbose_name_plural': 'Ventas por cuotas',
                'db_table': 'ventas_caja_venta_cuotas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('id_venta_cuotas', models.ForeignKey(db_column='id_venta_cuotas', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='ventas_caja.ventacuotas')),
            ],
            options={
                'verbose_name': 'Cuota de venta',
                'verbose_name_plural': 'Cuotas de venta',
                'db_table': 'ventas_caja_cuota_venta',
                'ordering': ['id_venta_cuotas', 'numero_cuota'],
                'unique_together': {('id_venta_cuotas', 'numero_cuota')},
            },
        ),
    ]
