# Generated by Django 6.0.4 on 2026-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_diagnosticocapilar'),
        ('ventas_caja', '0007_ventacuotas_cuotaventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaFidelizacion',
            fields=[
                ('id_campania', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_condicion', models.CharField(choices=[('VISITAS', 'Cantidad de visitas'), ('SERVICIOS', 'Servicios acumulados'), ('MONTO', 'Monto acumulado')], max_length=30)),
                ('valor_condicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_beneficio', models.CharField(choices=[('DESCUENTO_PORCENTAJE', 'Descuento porcentual'), ('DESCUENTO_MONTO', 'Descuento por monto'), ('SERVICIO_GRATIS', 'Servicio gratis'), ('PRODUCTO_GRATIS', 'Producto gratis')], max_length=30)),
                ('valor_beneficio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beneficio', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('FINALIZADA', 'Finalizada')], default='PROGRAMADA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('servicios_aplicables', models.ManyToManyField(blank=True, related_name='campanias_fidelizacion', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Campania de fidelizacion',
                'verbose_name_plural': 'Campanias de fidelizacion',
                'db_table': 'ventas_caja_campania_fidelizacion',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
    ]
