# Generated by Django 6.0.4 on 2026-06-22 20:59

import django.db.models.deletion
from django.db import migrations, models


PERMISOS_BASE = [
    ('usuarios.ver', 'Ver usuarios', 'usuarios', 'ver'),
    ('usuarios.crear', 'Crear usuarios', 'usuarios', 'crear'),
    ('usuarios.editar', 'Editar usuarios', 'usuarios', 'editar'),
    ('usuarios.eliminar', 'Eliminar usuarios', 'usuarios', 'eliminar'),
    ('roles.ver', 'Ver roles', 'roles', 'ver'),
    ('roles.crear', 'Crear roles', 'roles', 'crear'),
    ('roles.editar', 'Editar roles', 'roles', 'editar'),
    ('roles.eliminar', 'Eliminar roles', 'roles', 'eliminar'),
    ('roles.asignar_permisos', 'Asignar permisos a roles', 'roles', 'asignar_permisos'),
    ('barberos.ver', 'Ver barberos', 'barberos', 'ver'),
    ('barberos.crear', 'Crear barberos', 'barberos', 'crear'),
    ('barberos.editar', 'Editar barberos', 'barberos', 'editar'),
    ('barberos.eliminar', 'Eliminar barberos', 'barberos', 'eliminar'),
    ('clientes.ver', 'Ver clientes', 'clientes', 'ver'),
    ('clientes.crear', 'Crear clientes', 'clientes', 'crear'),
    ('clientes.editar', 'Editar clientes', 'clientes', 'editar'),
    ('servicios.ver', 'Ver servicios', 'servicios', 'ver'),
    ('servicios.crear', 'Crear servicios', 'servicios', 'crear'),
    ('servicios.editar', 'Editar servicios', 'servicios', 'editar'),
    ('servicios.eliminar', 'Eliminar servicios', 'servicios', 'eliminar'),
    ('promociones.ver', 'Ver promociones', 'promociones', 'ver'),
    ('promociones.crear', 'Crear promociones', 'promociones', 'crear'),
    ('promociones.editar', 'Editar promociones', 'promociones', 'editar'),
    ('promociones.eliminar', 'Eliminar promociones', 'promociones', 'eliminar'),
    ('citas.ver', 'Ver citas', 'citas', 'ver'),
    ('citas.ver_propias', 'Ver citas propias', 'citas', 'ver_propias'),
    ('citas.crear', 'Crear citas', 'citas', 'crear'),
    ('citas.editar', 'Editar citas', 'citas', 'editar'),
    ('citas.cancelar', 'Cancelar citas', 'citas', 'cancelar'),
    ('citas.editar_estado', 'Editar estado de cita', 'citas', 'editar_estado'),
    ('inventario.ver', 'Ver inventario', 'inventario', 'ver'),
    ('inventario.crear', 'Crear productos e insumos', 'inventario', 'crear'),
    ('inventario.editar', 'Editar inventario', 'inventario', 'editar'),
    ('inventario.eliminar', 'Eliminar inventario', 'inventario', 'eliminar'),
    ('inventario.movimientos', 'Registrar movimientos de inventario', 'inventario', 'movimientos'),
    ('ventas.ver', 'Ver ventas', 'ventas', 'ver'),
    ('ventas.crear', 'Crear ventas', 'ventas', 'crear'),
    ('ventas.anular', 'Anular ventas', 'ventas', 'anular'),
    ('caja.ver', 'Ver caja', 'caja', 'ver'),
    ('caja.abrir', 'Abrir caja', 'caja', 'abrir'),
    ('caja.cerrar', 'Cerrar caja', 'caja', 'cerrar'),
    ('caja.movimientos.ver', 'Ver movimientos de caja', 'caja', 'movimientos.ver'),
    ('caja.movimientos.crear', 'Crear movimientos de caja', 'caja', 'movimientos.crear'),
    ('caja.movimientos.anular', 'Anular movimientos de caja', 'caja', 'movimientos.anular'),
    ('metodos_pago.ver', 'Ver metodos de pago', 'metodos_pago', 'ver'),
    ('metodos_pago.crear', 'Crear metodos de pago', 'metodos_pago', 'crear'),
    ('metodos_pago.editar', 'Editar metodos de pago', 'metodos_pago', 'editar'),
    ('reportes.ver', 'Ver reportes', 'reportes', 'ver'),
    ('reportes.exportar', 'Exportar reportes', 'reportes', 'exportar'),
    ('notificaciones.ver', 'Ver notificaciones', 'notificaciones', 'ver'),
    ('notificaciones.crear', 'Crear notificaciones', 'notificaciones', 'crear'),
    ('notificaciones.enviar', 'Enviar notificaciones', 'notificaciones', 'enviar'),
    ('bitacora.ver', 'Ver bitacora', 'bitacora', 'ver'),
    ('horarios.ver', 'Ver horarios', 'horarios', 'ver'),
    ('horarios.crear', 'Crear horarios', 'horarios', 'crear'),
    ('horarios.editar', 'Editar horarios', 'horarios', 'editar'),
    ('asistencia.ver', 'Ver asistencia', 'asistencia', 'ver'),
    ('asistencia.crear', 'Crear asistencia', 'asistencia', 'crear'),
    ('asistencia.editar', 'Editar asistencia', 'asistencia', 'editar'),
    ('comisiones.ver', 'Ver comisiones', 'comisiones', 'ver'),
    ('comisiones.ver_propias', 'Ver comisiones propias', 'comisiones', 'ver_propias'),
]

PERMISOS_POR_ROL = {
    'barbero': [
        'servicios.ver',
        'promociones.ver',
        'citas.ver',
        'citas.editar_estado',
        'horarios.ver',
        'asistencia.ver',
        'comisiones.ver_propias',
        'notificaciones.ver',
    ],
    'cliente': [
        'servicios.ver',
        'promociones.ver',
        'citas.crear',
        'citas.ver_propias',
        'citas.cancelar',
        'notificaciones.ver',
    ],
    'cajero': [
        'clientes.ver',
        'servicios.ver',
        'promociones.ver',
        'ventas.ver',
        'ventas.crear',
        'ventas.anular',
        'caja.ver',
        'caja.abrir',
        'caja.cerrar',
        'caja.movimientos.ver',
        'caja.movimientos.crear',
        'caja.movimientos.anular',
        'metodos_pago.ver',
    ],
    'recepcionista': [
        'clientes.ver',
        'clientes.crear',
        'clientes.editar',
        'servicios.ver',
        'promociones.ver',
        'citas.ver',
        'citas.crear',
        'citas.editar',
        'citas.cancelar',
    ],
}


def cargar_permisos_base(apps, schema_editor):
    Permiso = apps.get_model('seguridad', 'Permiso')
    Rol = apps.get_model('seguridad', 'Rol')
    RolPermiso = apps.get_model('seguridad', 'RolPermiso')

    permisos_por_codigo = {}
    for codigo, nombre, modulo, accion in PERMISOS_BASE:
        permiso, _ = Permiso.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'modulo': modulo,
                'accion': accion,
                'descripcion': nombre,
            },
        )
        permisos_por_codigo[codigo] = permiso

    for rol in Rol.objects.all():
        nombre_rol = rol.nombre.lower()
        if nombre_rol == 'administrador':
            codigos = list(permisos_por_codigo.keys())
        else:
            codigos = PERMISOS_POR_ROL.get(nombre_rol, [])

        RolPermiso.objects.bulk_create([
            RolPermiso(rol=rol, permiso=permisos_por_codigo[codigo])
            for codigo in codigos
            if codigo in permisos_por_codigo
        ], ignore_conflicts=True)


def eliminar_permisos_base(apps, schema_editor):
    Permiso = apps.get_model('seguridad', 'Permiso')
    Permiso.objects.filter(codigo__in=[codigo for codigo, _, _, _ in PERMISOS_BASE]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': '"seguridad"."permiso"',
                'ordering': ['modulo', 'accion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='seguridad.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='seguridad.rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
                'db_table': '"seguridad"."rol_permiso"',
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.AddField(
            model_name='permiso',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='permisos', through='seguridad.RolPermiso', to='seguridad.rol'),
        ),
        migrations.RunPython(cargar_permisos_base, eliminar_permisos_base),
    ]
