# Generated by Django 6.0.4 on 2026-06-22 21:25

from django.db import migrations


PERMISOS_ATENCIONES = [
    ('atenciones.ver', 'Ver atenciones', 'atenciones', 'ver'),
    ('atenciones.iniciar', 'Iniciar atenciones', 'atenciones', 'iniciar'),
    ('atenciones.agregar_servicios', 'Agregar servicios a atenciones', 'atenciones', 'agregar_servicios'),
    ('atenciones.finalizar', 'Finalizar atenciones', 'atenciones', 'finalizar'),
    ('atenciones.cancelar', 'Cancelar atenciones', 'atenciones', 'cancelar'),
    ('atenciones.no_asistio', 'Marcar no asistio', 'atenciones', 'no_asistio'),
]


def cargar_permisos_atenciones(apps, schema_editor):
    Permiso = apps.get_model('seguridad', 'Permiso')
    Rol = apps.get_model('seguridad', 'Rol')
    RolPermiso = apps.get_model('seguridad', 'RolPermiso')

    permisos = {}
    for codigo, nombre, modulo, accion in PERMISOS_ATENCIONES:
        permiso, _ = Permiso.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'modulo': modulo,
                'accion': accion,
                'descripcion': nombre,
            },
        )
        permisos[codigo] = permiso

    for rol in Rol.objects.all():
        nombre = rol.nombre.lower()
        if nombre == 'administrador':
            codigos = list(permisos.keys())
        elif nombre == 'barbero':
            codigos = [
                'atenciones.ver',
                'atenciones.iniciar',
                'atenciones.agregar_servicios',
                'atenciones.finalizar',
                'atenciones.cancelar',
                'atenciones.no_asistio',
            ]
        else:
            codigos = []

        RolPermiso.objects.bulk_create([
            RolPermiso(rol=rol, permiso=permisos[codigo])
            for codigo in codigos
        ], ignore_conflicts=True)


def eliminar_permisos_atenciones(apps, schema_editor):
    Permiso = apps.get_model('seguridad', 'Permiso')
    Permiso.objects.filter(codigo__in=[codigo for codigo, _, _, _ in PERMISOS_ATENCIONES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_permiso_rolpermiso_permiso_roles'),
    ]

    operations = [
        migrations.RunPython(cargar_permisos_atenciones, eliminar_permisos_atenciones),
    ]
