# Generated by Django 6.0.4 on 2026-07-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_permisos_atenciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoLaboralPersonal',
            fields=[
                ('id_permiso_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_barbero', models.ForeignKey(db_column='codigo_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='permisos_laborales', to='seguridad.usuario')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_laborales_registrados', to='seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Permiso laboral del personal',
                'verbose_name_plural': 'Permisos laborales del personal',
                'db_table': '"seguridad"."permiso_laboral_personal"',
                'ordering': ['-fecha_inicio', 'codigo_barbero'],
            },
        ),
    ]
